FROM node:18
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
# para frontend y backend
RUN chmod -R +x node_modules/.bin
#CMD ["node", "server.js"]
CMD ["npm", "run", "dev"]
EXPOSE 5000
